name: develop-CD
on:
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      working-directory: .


    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Print current branch name
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "Checked out branch: $BRANCH_NAME"
